TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 32
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_FILE_PATH: "checkpoints/checkpoint_epoch_00056_100.pyth"
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  DECODING_BACKEND: "pyav"
  PATH_TO_DATA_DIR: "/u01/khienpv1/manvd1/action-recognition/data/kinetics-400/val"
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: cosine
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 10
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 20
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_FILE_PATH: "checkpoints/checkpoint_epoch_00056_100.pyth"
DATA_LOADER:
  NUM_WORKERS: 24
  PIN_MEMORY: True
  ENABLE_MULTI_THREAD_DECODE: True
TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: "/u01/khienpv1/manvd1/action-recognition/data/kinetics-400/class_id_mapping.json"
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: "/u01/khienpv1/manvd1/action-recognition/data/kinetics-400/subset_classes.txt"
                 # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized in the confusion matrix.
  HISTOGRAM:
    ENABLE: True
    TOPK: 5   # Top-k most frequently predicted classes for each class in the dataset.
    SUBSET_PATH: "/u01/khienpv1/manvd1/action-recognition/data/kinetics-400/subset_classes.txt"
                 # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized with histograms.

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "output/test/add-100"
